### PR TITLE
Pow20

### PR DESCRIPTION
**Pull request by pow20**
Pow20 is a proof of work protocol that extends Brc20 with a handful of extra rules for minting and deploying a token outlined here https://protocol.pow20.io

2 new fields introduced into the deploy 
`difficulty` is number of leading 0's required by the double sha 256 of the solution
`startingBlock` is the block where minting begins, the blockheader is included in the solution.  This prevents mining in secret by deployer 
```
{
  "p": "pow-20",
  "op": "deploy",
  "tick": "DOTI",
  "max": "21000000",
  "lim": "1000",
  "difficulty": "5",
  "startBlock": "875000"
  "dec": "8" // max 15
  "icon": "534cede12f90729d961dbdaf7dc889e9ac6567fd43759097567bca2f2791dcd8i0"
}
```

1 new field introduced to the mint inscription
```
{
  "p": "pow-20",
  "op": "mint",
  "tick": "DOTI",
  "amt": "1000",
  "solution": "<TICK>:<BTC_ADDRESS>:<START_BLOCK_HEADER>:<NONCE>"
}
```

New Indexer Rules
 - Is the address the same address found in the inscription? Must be true
 - Does the solution contain the correct START_BLOCK_HEADER header for the startBlock found in the deploy inscription? Must be true
 - Does the double sha256 hash of the solution meet the difficulty found in the deploy inscription? Must be true
 - Has the solution been seen before? Must be false

1 Open question is how can we get a url to report to and get a consensus view of Pow20

### CODE REVIEW

**Comment by samedcildir** [comment]
Thank you for the PR, we really appreciate it. 

I've reviewed the code and there are several changes that I think would make this module better:
- All important event pieces should be included in `block_event_str` for light clients to check and validate, so if you add `solution`for mint event and `startBlock` and `difficulty` to deploy event in `get_event_str` that would make the final hash more complete.
- Does vindicated inscriptions valid in pow20? You've removed `cursed_for_brc20` check which is actually exactly the same as vindicated charm but since we've implemented it before vindicated charm is released, we've named it differently.
- In "handle mint" part, a `"solution" not in js` check is needed since a pow-20 mint without solution would crash this indexer.

If you open `report_hashes` part at the end of the code, we can create a new tab for Pow20 on opi.network where you can get a consensus view table.

**Comment by pow20** [comment]
Thank you, I really appreciate your time to review

I have addressed the concerns raised 
 - adding custom fields to hashed strings
 - extra check on solution
 - uncomment reporting 
 
 If you could open up that endpoint so we can start reporting that would be appreciated.  Currently is returns a 400

**Comment by pow20** [comment]
@samedcildir I have also added back the filter for cursed brc20

**Comment by samedcildir** [comment]
Thank you for the changes, I'll merge this and enable pow20 reporting on api.opi.network 👍

**Pull request merged**
